### ISSUE TITLE
[PE-D][Tester B] Functionality Error for add_interview 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-3/tp#159]
**Edge case result for add_interview command:**

![Screenshot 2024-04-05 at 4.18.35 PM.png](https://raw.githubusercontent.com/YuvBindal/ped/main/files/8c1f58c1-81bd-4e6d-a00e-96de4a801902.png)

![Screenshot 2024-04-05 at 4.19.01 PM.png](https://raw.githubusercontent.com/YuvBindal/ped/main/files/1a50a890-65a1-4817-975b-f3ce07662405.png)

As shown by the images above, when inputting a valid applicant phone number with a valid interviewer phone number when both numbers are the same, the command is detecting the numbers in an incorrect format. For instance, here the applicant number and interviewer number here are 81239123 and 81239133 is being detected as 88888888 and 88889999 respectively. 

Regards!

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: YuvBindal/ped#4

**Comment by macareonie** [comment]
eye issue
