### ISSUE TITLE
[PE-D][Tester C] The timing should put up an error message 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-3/tp#202]
![Screenshot 2024-04-05 at 4.59.26 PM.png](https://raw.githubusercontent.com/kab-dot/ped/main/files/4b500331-9b35-474d-9b1f-13e963f39498.png)
the timing should not be working backwards, eg should only accept timing forwards

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: kab-dot/ped#10

**Comment by macareonie** [comment]
duplicate
