### ISSUE TITLE
[PE-D][Tester E] Remark command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-3/tp#218]
Remark command is not mentioned anywhere in UG except in GUI as mentioned before but the remark command still works which should not be the case if there is no mention and it is not intended

![image.png](https://raw.githubusercontent.com/yorklim/ped/main/files/4838e6a7-3b67-4ab8-b6cf-9819b45d9680.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: yorklim/ped#18

**Comment by macareonie** [comment]
duplicate
