### ISSUE TITLE
[PE-D][Tester A] filter_interviews_by_date doesn't work properly when no interview found.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F11-3/tp#225]
# before command

![image.png](https://raw.githubusercontent.com/Li-Zizhen/ped/main/files/8dc7d1b0-1cd8-47b8-ab15-270b3a596c3d.png)

# after command

![image.png](https://raw.githubusercontent.com/Li-Zizhen/ped/main/files/4501292d-04c0-4193-a3e9-1335be97f285.png)

## If no interviews are found, then the upcoming interviews section at the right should be empty, however, there are still interviews in that section.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Li-Zizhen/ped#10

**Comment by macareonie** [comment]
Update error message and explicitly state behaviour in UG
