### ISSUE TITLE
[PE-D][Tester A] delete_interview command not working for index 1

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-3/tp#226]
![image.png](https://raw.githubusercontent.com/Li-Zizhen/ped/main/files/d4ad82cf-1be6-4e3b-8cf9-0a44dfece975.png)

## There are some upcoming interviews, however, when I want to delete the first interview using delete_interview 1, the system doesn't respond to my command.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Li-Zizhen/ped#11

**Comment by macareonie** [comment]
Remove edit command functionality.
Block delete person command if person is currently assigned to an interview
