### ISSUE TITLE
[PE-D][Tester A] Unfunctioal Remark feature

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-F11-3/tp#229]
![image.png](https://raw.githubusercontent.com/Li-Zizhen/ped/main/files/a407cbae-2671-4bd6-81d9-ded1ba6b59d9.png)

## Every person has the remark field, but there is no command to add a remark. Please consider completing this feature.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: Li-Zizhen/ped#14

**Comment by macareonie** [comment]
Add remark documentation to UG and help menu
